### ISSUE TITLE
Python 3.9 support

### ISSUE THREAD

**Issue by romanw** [pimoroni/cap1xxx#19]
Using python 3.9, cap1xxx fails with the following error...

Traceback (most recent call last):
  File "/home/user/projects/python/displayotron/test.py", line 53, in <module>
    def handle_up(ch, evt):
  File "/home/user/projects/python/displayotron/venv/lib/python3.9/site-packages/dothat/touch.py", line 42, in register
    _cap1166.on(channel=button, event='press', handler=handler)
  File "/home/user/projects/python/displayotron/venv/lib/python3.9/site-packages/cap1xxx.py", line 386, in on
    self.start_watching()
  File "/home/user/projects/python/displayotron/venv/lib/python3.9/site-packages/cap1xxx.py", line 400, in start_watching
    self.async_poll.start()
  File "/home/user/projects/python/displayotron/venv/lib/python3.9/site-packages/cap1xxx.py", line 208, in start
    if self.isAlive() == False:
AttributeError: 'AsyncWorker' object has no attribute 'isAlive'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/user/projects/python/displayotron/venv/lib/python3.9/site-packages/cap1xxx.py", line 409, in stop_watching
    self.async_poll.stop()
  File "/home/user/projects/python/displayotron/venv/lib/python3.9/site-packages/cap1xxx.py", line 213, in stop
    if self.isAlive() == True:
AttributeError: 'AsyncWorker' object has no attribute 'isAlive'
Exception ignored in: <function Cap1xxx.__del__ at 0x75d62850>
Traceback (most recent call last):
  File "/home/user/projects/python/displayotron/venv/lib/python3.9/site-packages/cap1xxx.py", line 522, in __del__
  File "/home/user/projects/python/displayotron/venv/lib/python3.9/site-packages/cap1xxx.py", line 409, in stop_watching
  File "/home/user/projects/python/displayotron/venv/lib/python3.9/site-packages/cap1xxx.py", line 213, in stop
AttributeError: 'AsyncWorker' object has no attribute 'isAlive'

Apparently thread.isAlive() is no longer available in python 3.9; thread.is_alive() is the new name!  Global search and replace from 'isAlive' to 'is_alive' in cap1xxx.py seems to fix the issue.

**Comment by Gadgetoid** [comment]
I'm a little overdue, but thank you!
